name: Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -race -v ./...

      - name: Code Coverage
        run: |
          go test -v -coverprofile=cover.out -covermode=atomic .
          go tool cover -html=cover.out -o cover.html

      - name: Upload Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
          flags: unittests
          verbose: true